import React from 'react';
import { Container, Row, Col, Carousel } from 'react-bootstrap';
import { FaQuoteRight, FaStar, FaComments } from 'react-icons/fa';
import './style/testimonial.css';


const TestimonialsSection = () => {
  const testimonials = [
    {
      name: 'Luna J.',
      role: 'Startup Founder',
      company: 'TechVision Inc.',
      image: 'https://randomuser.me/api/portraits/women/1.jpg',
      text: 'The features generated by AI are fantastic! In about five minutes, I created my full website, and it looks really professional. There are countless ways to customize it.',
      rating: 5,
    },
    {
      name: 'Adam K.',
      role: 'Freelance Designer',
      company: 'Creative Studio',
      image: 'https://randomuser.me/api/portraits/men/2.jpg',
      text: 'As a designer, I first doubted this website, but the AI recommendations were outstanding. My clients are delighted with the outcome, and it saved me hours of labor.',
      rating: 5,
    },
    {
      name: 'Ruby S.',
      role: 'E-commerce Owner',
      company: 'Fashion Boutique',
      image: 'https://randomuser.me/api/portraits/women/3.jpg',
      text: 'The integration of e-commerce was flawless. My online store launched swiftly, and more sales are being generated by the AI-powered product recommendations.',
      rating: 5,
    },
    {
      name: 'Michael T.',
      role: 'Restaurant Owner',
      company: 'Gourmet Dining',
      image: 'https://randomuser.me/api/portraits/men/4.jpg',
      text: 'The website creator has a thorough understanding of restaurant requirements. The reservation system and menu layout are immaculate.',
      rating: 5,
    },
  ];

  return (
    <section className="testimonials-section" id="testimonials">
      <Container>
        <div className="section-header text-center" data-aos="fade-up">
          <h2 className="section-title">
          <span className="animated-icon-container">
              <FaComments className="animated-icon" />
          </span>
            What Our Users Say</h2>
          <div className="animated-underline"></div>
          <p className="section-description">
          Opinions from our community of successful website builders.

          </p>
        </div>
        <Row className="justify-content-center">
          <Col lg={10}>
            <Carousel controls indicators fade className="custom-carousel">
              {testimonials.map((testimonial, index) => (
                <Carousel.Item key={index}>
                  <div className="testimonial-item text-center" data-aos="fade-up" data-aos-delay={index * 100}>
                    <div className="testimonial-content">
                      <div className="quote-icon">
                        <FaQuoteRight />
                      </div>
                      <p className="testimonial-text">{testimonial.text}</p>
                      <div className="rating">
                        {[...Array(testimonial.rating)].map((_, i) => (
                          <FaStar key={i} className="star-icon" />
                        ))}
                      </div>
                    </div>
                    <div className="testimonial-author">
                      <img src={testimonial.image} alt={testimonial.name} className="author-image" />
                      <div className="author-info">
                        <h4 className="author-name">{testimonial.name}</h4>
                        <p className="author-role">{testimonial.role}</p>
                        <p className="author-company">{testimonial.company}</p>
                      </div>
                    </div>
                  </div>
                </Carousel.Item>
              ))}
            </Carousel>
          </Col>
        </Row>
      </Container>
    </section>
  );
};

export default TestimonialsSection;
